### ISSUE TITLE
ConnectCaller Method connection timeout

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-example-ivr#1]
I always get connection timeout when calling connectCaller Method, here is error output

> Error: Connection timeout
>     at Timeout.setTimeout [as _onTimeout] (C:\TFS2\Viases-Cloud Project\Viases_Cloud.IVREngine\node_modules\drachtio-fsmrf\lib\mediaserver.js:283:22)
>     at ontimeout (timers.js:427:11)
>     at tryOnTimeout (timers.js:289:5)
>     at listOnTimeout (timers.js:252:5)
>     at Timer.processTimers (timers.js:212:10)

My drachtio-server and freeswitch docker image runs on different servers.

Update: I also tried to run freeswitch docker image on the same server with drachtio-server, still I get timeout.

**Comment by salihy** [comment]
I think connection::ready event does not get triggered. Freeswitch either cannot create connection or cannot let drachtio-fsmrf channel is created. _onNewCall method is never called.

mediaserver.js

this._server.on('connection::ready', this._onNewCall.bind(this)) ;
